<?php
include("Head.php");
include("Navbar_Privacy.php");
include("Header_Privacy.php");
include("Content_Privacy.php");
include("About_Us_Footer.php");
include("Footer.php");
include("Js.php");
?>